extensions:
  health_check:
    endpoint: 0.0.0.0:13133

receivers:
  zipkin:
    endpoint: 0.0.0.0:9411

processors:
  batch:

exporters:
  logging:
    # Defines log level for the logging exporter
    loglevel: debug
  awsxray:

service:
  pipelines:
    traces:
      receivers: [zipkin]
      processors: [batch]
      # HINT: add the logging exporter to get traces logged to the collector output, e.g [logging, awsxray]
      exporters: [awsxray]
  extensions: [health_check]
