extensions:
  health_check:
    endpoint: 0.0.0.0:13133

receivers:
  zipkin:

processors:
  batch:

exporters:
  logging:
    loglevel: debug
  awsxray:
    region: 'us-west-2'

service:
  pipelines:
    traces:
      receivers: [zipkin]
      processors: [batch]
      exporters: [logging, awsxray]
  extensions: [health_check]
