on:
  push:
    branches:
      - "master"
  pull_request:

jobs:
  lint-and-build:
    runs-on: ubuntu-20.04
    steps:
      - uses: action/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - name: npm lint
        run: npx eslint . --ext .ts
      - name: /aws typescript build 
        run: |
          pushd aws
          npm install
          npx tsc --build
          popd
